### ISSUE TITLE
_tkinter.TclError: bad window path name ".!ctkscrollabledropdownframe"

### ISSUE THREAD

**Issue by rudymohammadbali** [Akascape/CTkScrollableDropdown#14]
**When destroying the frame that _ctkscrollabledropdownframe_ inside it. this error occurs:**

```
 Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "E:\Python\ctkWidgets\main.py", line 81, in <lambda>
    self.attach.winfo_toplevel().bind("<ButtonPress>", lambda e: self._withdraw() if not self.disable else None,
                                                                 ^^^^^^^^^^^^^^^^
  File "E:\Python\ctkWidgets\main.py", line 168, in _withdraw
    if self.winfo_viewable() and self.hide:
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1294, in winfo_viewable
    self.tk.call('winfo', 'viewable', self._w))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bad window path name ".!ctkscrollabledropdownframe"
```

**Comment by rudymohammadbali** [comment]
**The way I resolve this error is by:**

Create CTkScrollableDropdownFrame
`self.my_dropdown = CTkScrollableDropdownFrame(my_optionmenu, values=values)`

Before destroying main frame:
`self.my_dropdown.destroy_popup()`

**Comment by Akascape** [comment]
@iamironman0 Please try the new version
