### ISSUE TITLE
Image_values Exception

### ISSUE THREAD

**Issue by Demsli** [Akascape/CTkScrollableDropdown#40]
Greetings everyone. Just found this widget, but dont get how image_values parametre works. I get an exception when trying to pass it. Here the code sample:

import customtkinter
from CTkScrollableDropdown import *
import os

image_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), "cp_images")
image1 = os.path.join(image_path, "PS-icon.ico")
image2 = os.path.join(image_path, "PS-icon.ico")
image3 = os.path.join(image_path, "PS-icon.ico")
class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()
        optionmenu = customtkinter.CTkOptionMenu(self, width=240)
        optionmenu.pack(fill="x", padx=10, pady=10)
        CTkScrollableDropdown(attach=optionmenu, values=['a', 'b', 'c'], image_values=[image1, image2, image3])

app = App()
app.mainloop()

Here is the log of what I get: UserWarning: CTkButton Warning: Given image is not CTkImage but <class 'str'>. Image can not be scaled on HighDPI displays, use CTkImage instead.

  warnings.warn(f"{type(self).__name__} Warning: Given image is not CTkImage but {type(image)}. Image can not be scaled on HighDPI displays, use CTkImage instead.\n")
Traceback (most recent call last):
  File "c:\Users\user\Documents\Portable Python-3.10.5 x64\gif_tests.py", line 110, in <module>
    app = App()
          ^^^^^
  File "c:\Users\user\Documents\Portable Python-3.10.5 x64\gif_tests.py", line 107, in __init__
    CTkScrollableDropdown(attach=optionmenu, values=['a', 'b', 'c'], image_values=[image1, image2, image3])
  File "c:\Users\user\Documents\Portable Python-3.10.5 x64\CTkScrollableDropdown\ctk_scrollable_dropdown.py", line 102, in __init__
    self._init_buttons(**button_kwargs)
  File "c:\Users\user\Documents\Portable Python-3.10.5 x64\CTkScrollableDropdown\ctk_scrollable_dropdown.py", line 184, in _init_buttons
    self.widgets[self.i] = customtkinter.CTkButton(self.frame,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 106, in __init__
    self._draw()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 264, in _draw
    self._update_image()  # set image
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 176, in _update_image
    self._image_label.configure(image=self._image)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1721, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1711, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: image "C:\Users\user\Documents\Portable Python-3.10.5 x64\cp_images\PS-icon.ico" doesn't exist

It is weird, the image does exist in this folder. I tried .png instead of .ico too - same issue.

Customtkinter version: 5.2.2 
Python version: 3.11.9

**Comment by Akascape** [comment]
@Demsli Pass image values like this:
```python
image_values=[customtkinter.CTkImage(Image.open("image1.png")),
                         customtkinter.CTkImage(Image.open("image2.png")), 
                         None]
```
